apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: {{eks-namespace}}

labels:
- includeSelectors: true
  pairs:
    app: edgecond

patches:
- ./deployment-patches.yaml
- ./persistVolume-patches.yaml
- ./secretproviderclass-patches.yaml

resources:
- ./persistvolume.yaml

configMapGenerator:
- name: configmap-edgecond
  envs:
  - ./configmap.env
