apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-edgecond-{{prj-name}}
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-edgecond
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{efs-id}}
