apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-edge-conductor
spec:
  parameters:
    objects: |
      - objectName: "{{secret-name}}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "dbusername"
          - path: "password"
            objectAlias: "dbpassword"
          - path: "host"
            objectAlias: "dbhost"
          - path: "port"
            objectAlias: "dbport"

