apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-edge-conductor
spec:
  provider: aws
  secretObjects:
    - secretName: secret-edgecond
      type: Opaque
      data:
        - key: "MYSQL_USER"
          objectName: "dbusername"
        - key: "MYSQL_PSWD"
          objectName: "dbpassword"
        - key: "MYSQL_HOST"
          objectName: "dbhost"
        - key: "MYSQL_PORT"
          objectName: "dbport"
  parameters:
    objects: <PATCH_ME>
