apiVersion: v1
kind: Service
metadata:
  name: svc-edgecond-backend
spec:
  type: NodePort
  selector:
    deployment: edgecond-backend
---
apiVersion: v1
kind: Service
metadata:
  name: svc-edgecond-frontend
spec:
  type: NodePort
  selector:
    deployment: edgecond-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: svc-edgecond-internal
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 31020
    protocol: TCP
    targetPort: 31020
  selector:
    deployment: edgecond-backend
